config/routes.rb
Rails.application.routes.draw do
  root 'tracks#index'

  resources :tracks do
    collection do
      get '/update' => 'tracks/update#index'
      post '/update' => 'tracks/update#create'
    end
  end
  resources :artists, :only => [:index, :show]
  get '/lyrics' => 'lyrics#index'

  get '/activity/all' => 'activity#all'
  get '/activity/recent' => 'activity#recent'

  namespace :api do
    resources :tracks, only: [:index] do
      post :search, on: :collection
    end
  end
end

app/models/album.rb
class Album
  include Mongoid::Document

  embedded_in :track

  field :name, type: String
  field :mbid, type: String

  index({ mbid: 1 }, { unique: true, name: "mbid_index" })

  def to_s
    self.name
  end
end

app/models/artist.rb
class Artist
  include Mongoid::Document

  embedded_in :track

  field :name, type: String
  field :mbid, type: String

  index({ mbid: 1 }, { unique: true, name: "mbid_index" })

  def to_s
    self.name
  end
end

app/models/punchcard_generator.rb
class PunchcardGenerator
  attr_accessor :data
  def initialize(data)
    @data = data
  end

  def generate
    builder.to_xml
  end

  def builder
    Nokogiri::XML::Builder.new do |xml|
      xml.svg(xmlns: 'http://www.w3.org/2000/svg', width: 920, height: 520, class: 'viz') do
        generate_days(xml)
        generate_legend(xml)
      end
    end
  end

  def generate_days(xml)
    xml.g(transform: 'translate(0,0)') do
      (0..6).map do |day|
        xml.g(class: 'day', transform: "translate(0, #{9 + day * 67})") do

          xml.line(x1: 0, y1: 60, x2: 920, y2: 60, class: 'axis')
          xml.text_(class: 'label', dy: 30) do
            xml.text(days[day])
          end

          (0..23).map do |hour|
            xml.g(class: 'hour', transform: "translate(#{104 + hour * 34}, 0)", width: 31) do
              xml.line(x1: 0, y1: "#{hour.even? ? 45 : 50}", x2: 0, y2: 60, class: "axis #{hour.even? ? 'even' : 'odd'}")
              value = data[day][hour].to_f || 0.0
              r = radius * Math.sqrt(value / maximum)
              xml.circle(r: r, cy: 25, class: 'day')
            end
          end
        end
      end
    end
  end

  def generate_legend(xml)
    xml.g(transform: 'translate(0,0)') do
      (0..23).map do |hour|
        xml.text_('text-anchor' => 'middle', transform: "translate(#{104 + hour * 34}, 500)", class: 'label') do
          xml.text(hour)
        end
      end
    end
  end

  private

  def days
    ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
  end

  def maximum
    @maximum ||= data.values.map(&:values).flatten.max
  end

  def radius
    15.5
  end
end

app/models/track.rb
class Track
  include Mongoid::Document

  embeds_one :artist
  embeds_one :album

  field :name, type: String
  field :mbid, type: String
  field :uts, type: Integer

  index({ mbid: 1 }, { unique: true, name: "mbid_index" })
  index({ uts: 1 }, { name: "uts_index" })

  def to_s
    self.name
  end

  def listened_at
    Time.at(uts)
  end

  def self.recent
    timepoint = (Time.now - 29.days).beginning_of_day.to_i

    self.where(:uts.gte => timepoint)
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def all
    respond_to do |format|
      format.html do
        @data = all_activity
        @svg = punchcard
      end
      format.svg do
        render inline: punchcard, content_type: Mime::SVG
      end
    end
  end

  def recent
    render json: recent_activity
  end

  private

  def recent_activity
    @recent_activity ||= Tracks::Activity.new(Track.recent).group_by_day
  end

  def all_activity
    @all_activity ||= Tracks::Activity.new(Track.all).group_by_day_and_hour
  end

  def punchcard
    @punchcard ||= Punchcard.new(all_activity).generate
  end
end

app/controllers/api/tracks_controller.rb
class Api::TracksController < ApplicationController
  def index
    tracks = Track.limit(50).order_by(uts: 'desc')

    render json: tracks
  end

  def search
    tracks = Track.or([
      {'artist.name' => pattern},
      {'album.name' => pattern},
      {'name' => pattern}
    ]).limit(50).order_by(uts: 'desc')

    render json: tracks
  end

  private

  def pattern
    @pattern ||= /.*#{params[:name]}.*/i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  respond_to :html, :json

  def index
    @artists = Track.distinct('artist.name').sort

    respond_with(@artists)
  end

  def show
    @artist = params[:id]
    @tracks = Track.where('artist.name' => @artist).uniq(&:name).sort_by(&:name)

    respond_with({artist: @artist, tracks: @tracks})
  end
end

app/controllers/lyrics_controller.rb
class LyricsController < ApplicationController
  def index
    render plain: lyrics
  end

  private

  def lyrics
    Lyrics::Fetcher.new(params).get
  end
end

app/controllers/tracks/update_controller.rb
class Tracks::UpdateController < ApplicationController
  def index
  end

  def create
    pages = params[:pages].to_i
    Tracks::Updater.run(pages)
    render :nothing => true, :status => 200
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  respond_to :html, :json

  def index
    @tracks = Track.limit(50).order_by(uts: 'desc')
    respond_with(@tracks)
  end

  def update
    @track = Track.find_by(mbid: params[:mbid])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity/all.html.haml
%table
  - (0..23).each do |hour|
    %th= hour
  - (0..6).each do |day|
    %tr
      - (0..23).each do |hour|
        %td.span1= @data[day][hour]

= raw @svg

app/views/activity/show.html.haml
%table
  - (0..23).each do |hour|
    %th= hour
  - (0..6).each do |day|
    %tr
      - (0..23).each do |hour|
        %td.span1= @data[day][hour]

= raw @svg

app/views/artists/index.html.haml
- if @artists.blank?
  No artists yet.
- else
  %table
    - @artists.each do |artist|
      %tr
        %td.span6= link_to artist, artist_path(artist)

app/views/artists/show.html.haml
%h1= @artist

%ul
  - @tracks.each do |track|
    %li= track

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Soundly</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/index.haml
%div{'ng-app' => 'soundly'}
  %div{'ng-controller' => 'TracksController'}
    %input{'type' => 'text', 'ng-model' => 'name', 'ng-change' => 'search()', 'placeholder' => 'Search' }
    %table
      %thead
        %tr
          %th.span6 Track
          %th.span6 Artist
          %th.span6 Album
          %th.span6 Listened
      %tbody
        %tr{'ng-repeat' => 'track in tracks'}
          %td {{track.name}}
          %td {{track.artist}}
          %td {{track.album}}
          %td {{track.uts * 1000 | date:'yyyy-MM-dd HH:mm:ss Z'}}

app/views/tracks/index.html.haml
%div{'ng-app' => 'project'}
  %div{'ng-controller' => 'TracksController'}
    %input{'type' => 'text', 'ng-model' => 'name', 'ng-change' => 'search()', 'placeholder' => 'Search' }
    %table
      %thead
        %tr
          %th.span6 Track
          %th.span6 Artist
          %th.span6 Album
          %th.span6 Listened
      %tbody
        %tr{'ng-repeat' => 'track in tracks'}
          %td {{track.name}}
          %td {{track.artist}}
          %td {{track.album}}
          %td {{track.uts * 1000 | date:'yyyy-MM-dd HH:mm:ss Z'}}